server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/greendb
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      "[hibernate.format_sql]": true
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    #root: DEBUG
