server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/greendb
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      "[hibernate.format_sql]": true
  output:
    ansi:
      enabled: always
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftlh

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    #root: DEBUG
